<?php

/**
 * Organization Module — Quick Actions Configuration
 *
 * Registers organization management actions for the command palette.
 * These actions appear when the user presses Cmd+K / Ctrl+K.
 */
return [
    'quick_actions' => [
        [
            'id'          => 'organization.view_dashboard',
            'label'       => 'View Organization Dashboard',
            'description' => 'Go to the organization dashboard overview',
            'icon'        => 'fas fa-tachometer-alt',
            'action'      => 'navigate',
            'module'      => 'organization',
            'keywords'    => ['dashboard', 'home', 'overview', 'organization', 'org'],
            'category'    => 'Dashboard',
            'route'       => '/organization/dashboard-overview',
            'roles'       => ['super_admin', 'company_admin'],
        ],
        [
            'id'          => 'organization.add_company',
            'label'       => 'Add Company',
            'description' => 'Create a new company in the organization',
            'icon'        => 'fas fa-building',
            'action'      => 'navigate',
            'module'      => 'organization',
            'keywords'    => ['company', 'add', 'create', 'new', 'business', 'organization'],
            'category'    => 'Companies',
            'route'       => '/organization/companies',
            'permission'  => 'view_company',
            'roles'       => ['super_admin', 'company_admin'],
        ],
        [
            'id'          => 'organization.add_department',
            'label'       => 'Add Department',
            'description' => 'Create a new department in the organization structure',
            'icon'        => 'fas fa-layer-group',
            'action'      => 'navigate',
            'module'      => 'organization',
            'keywords'    => ['department', 'add', 'create', 'new', 'structure', 'org'],
            'category'    => 'Structure',
            'route'       => '/organization/departments',
            'permission'  => 'view_department',
            'roles'       => ['super_admin', 'company_admin'],
        ],
        [
            'id'          => 'organization.add_location',
            'label'       => 'Add Location',
            'description' => 'Add a new office or work location',
            'icon'        => 'fas fa-map-marker-alt',
            'action'      => 'navigate',
            'module'      => 'organization',
            'keywords'    => ['location', 'add', 'create', 'new', 'office', 'site', 'address'],
            'category'    => 'Locations',
            'route'       => '/organization/locations',
            'permission'  => 'view_location',
            'roles'       => ['super_admin', 'company_admin'],
        ],
        [
            'id'          => 'organization.add_branch',
            'label'       => 'Add Branch',
            'description' => 'Create a new company branch',
            'icon'        => 'fas fa-code-branch',
            'action'      => 'navigate',
            'module'      => 'organization',
            'keywords'    => ['branch', 'add', 'create', 'new', 'office', 'subsidiary'],
            'category'    => 'Companies',
            'route'       => '/organization/branches',
            'permission'  => 'view_branch',
            'roles'       => ['super_admin', 'company_admin'],
        ],
        [
            'id'          => 'organization.add_team',
            'label'       => 'Add Team',
            'description' => 'Create a new team in the organization',
            'icon'        => 'fas fa-users',
            'action'      => 'navigate',
            'module'      => 'organization',
            'keywords'    => ['team', 'add', 'create', 'new', 'group', 'people'],
            'category'    => 'Teams',
            'route'       => '/organization/teams',
            'permission'  => 'view_team',
            'roles'       => ['super_admin', 'company_admin'],
        ],
        [
            'id'          => 'organization.add_division',
            'label'       => 'Add Division',
            'description' => 'Create a new organizational division',
            'icon'        => 'fas fa-diagram-project',
            'action'      => 'navigate',
            'module'      => 'organization',
            'keywords'    => ['division', 'add', 'create', 'new', 'structure', 'unit'],
            'category'    => 'Structure',
            'route'       => '/organization/divisions',
            'permission'  => 'view_division',
            'roles'       => ['super_admin', 'company_admin'],
        ],
        [
            'id'          => 'organization.add_business_unit',
            'label'       => 'Add Business Unit',
            'description' => 'Create a new business unit',
            'icon'        => 'fas fa-briefcase',
            'action'      => 'navigate',
            'module'      => 'organization',
            'keywords'    => ['business', 'unit', 'add', 'create', 'new', 'bu'],
            'category'    => 'Companies',
            'route'       => '/organization/business-units',
            'permission'  => 'view_business_unit',
            'roles'       => ['super_admin', 'company_admin'],
        ],
        [
            'id'          => 'organization.reports',
            'label'       => 'Reports',
            'description' => 'View organization reports and analytics',
            'icon'        => 'fas fa-file-alt',
            'action'      => 'navigate',
            'module'      => 'organization',
            'keywords'    => ['reports', 'analytics', 'charts', 'data', 'insights'],
            'category'    => 'Reports',
            'route'       => '/organization/dashboard-reports-overview',
            'permission'  => 'view_reports_overview',
            'roles'       => ['super_admin', 'company_admin'],
        ],
    ],
];