<?php

return [
    'context_groups' => [
        'dashboard' => [
            'label' => 'Dashboard',
            'icon' => 'fas fa-tachometer-alt',
            'order' => 0,
            'route' => NULL,
            'url' => 'hr/dashboard',
            'permission' => 'view_hidden_dashboard',
            'roles' => ['*'],
        ],
        'my-portal' => [
            'label' => 'My Portal',
            'icon' => 'fas fa-user',
            'order' => 1,
            'route' => NULL,
            'url' => 'hr/my-portal',
            'permission' => 'view_my_portal',
            'roles' => ['*'],
        ],
        'Organization' => [
            'label' => 'Organization',
            'icon' => 'fas fa-building',
            'order' => 10000,
            'route' => NULL,
            'url' => 'hr/dashboard-organization-overview',
            'permission' => 'view_organization_overview',
            'roles' => ['*'],
        ],
        'people' => [
            'label' => 'People',
            'icon' => 'fas fa-user-tie',
            'order' => 999,
            'route' => NULL,
            'url' => 'hr/dashboard-people-overview',
            'roles' => ['*'],
        ],
        'manage' => [
            'label' => 'Manage',
            'icon' => 'fas fa-cogs',
            'order' => 1000,
            'route' => NULL,
            'url' => 'hr/dashboard-manage-overview',
            'permission' => 'view_manage_overview',
            'roles' => ['*'],
        ],
        'onboarding' => [
            'label' => 'Onboarding',
            'icon' => 'fas fa-user-check',
            'order' => 500,
            'route' => NULL,
            'url' => 'hr/onboarding-overview',
            'permission' => 'view_invitation',
            'roles' => ['*'],
        ],
    ],
    'contexts' => [
        'my-portal' => [
            [
                'key' => 'my_portal_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-home',
                'route' => '/hr/my-portal',
                'permission' => 'view_my_portal',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'my_profile',
                'label' => 'My Profile',
                'icon' => 'fas fa-user',
                'route' => '/hr/my-profile',
                'permission' => 'view_my_portal',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'leave_hub',
                'label' => 'Leave',
                'icon' => 'fas fa-calendar-alt',
                'route' => '/hr/leave-hub',
                'permission' => 'view_leave_hub',
                'order' => 3,
                'page_title' => NULL,
            ],
            [
                'key' => 'team_calendar',
                'label' => 'Team Calendar',
                'icon' => 'fas fa-calendar-alt',
                'route' => '/hr/my-team-calendar',
                'permission' => 'view_team_calendar',
                'order' => 4,
                'page_title' => NULL,
            ],
        ],
        'Organization' => [
            [
                'key' => 'company_profile_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-organization-overview',
                'permission' => 'view_company_profile_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'location',
                'label' => 'Locations',
                'icon' => 'fas fa-map-marker-alt',
                'route' => '/hr/locations',
                'permission' => 'view_location',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'company',
                'label' => 'Companies',
                'icon' => 'fas fa-building',
                'route' => '/hr/companies',
                'permission' => 'manage-system',
                'order' => 3,
                'page_title' => NULL,
            ],
            [
                'key' => 'department',
                'label' => 'Departments',
                'icon' => 'fas fa-sitemap',
                'route' => '/hr/departments',
                'permission' => 'view_department',
                'order' => 4,
                'page_title' => NULL,
            ],
        ],
        'people' => [
            [
                'key' => 'people_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-people-overview',
                'permission' => 'view_people_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee',
                'label' => 'Employees',
                'icon' => 'fas fa-user-tie',
                'route' => '/hr/employees',
                'permission' => 'view_employee',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_profile',
                'label' => 'Profiles',
                'icon' => 'fas fa-id-card',
                'route' => '/hr/employee-profiles',
                'permission' => 'view_employee_profile',
                'order' => 3,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_position',
                'label' => 'Current Jobs',
                'icon' => 'fas fa-briefcase',
                'route' => '/hr/employee-positions',
                'permission' => 'view_employee_position',
                'order' => 4,
                'page_title' => NULL,
            ],
            [
                'key' => 'team',
                'label' => 'Teams',
                'icon' => 'fas fa-user-friends',
                'route' => '/hr/teams',
                'permission' => 'view_team',
                'order' => 5,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_group',
                'label' => 'Employee Groups',
                'icon' => 'fas fa-layer-group',
                'route' => '/hr/employee-groups',
                'permission' => 'view_employee_group',
                'order' => 6,
                'page_title' => NULL,
            ],
        ],
        'manage' => [
            [
                'key' => 'manage_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-manage-overview',
                'permission' => 'view_manage_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'job_title',
                'label' => 'Job Titles',
                'icon' => 'fas fa-briefcase',
                'route' => '/hr/job-titles',
                'permission' => 'view_job_title',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'tag',
                'label' => 'Tags',
                'icon' => 'fas fa-tags',
                'route' => '/hr/tags',
                'permission' => 'view_tag',
                'order' => 3,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_job_history',
                'label' => 'Job History',
                'icon' => 'fas fa-history',
                'route' => '/hr/employee-job-histories',
                'permission' => 'view_employee_job_history',
                'order' => 4,
                'page_title' => NULL,
            ],
            [
                'key' => 'document',
                'label' => 'Documents',
                'icon' => 'fas fa-folder-open',
                'route' => '/hr/documents',
                'permission' => 'view_document',
                'order' => 5,
                'page_title' => NULL,
            ],
        ],
        'onboarding' => [
            [
                'key' => 'onboarding_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-home',
                'route' => '/hr/onboarding-overview',
                'permission' => 'view_invitation',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'invitation',
                'label' => 'Invitations',
                'icon' => 'fas fa-envelope',
                'route' => '/hr/invitations',
                'permission' => 'view_invitation',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_onboarding',
                'label' => 'Employee Onboarding',
                'icon' => 'fas fa-user-graduate',
                'route' => '/hr/employee-onboarding',
                'permission' => 'view_invitation',
                'order' => 3,
                'page_title' => NULL,
            ],
            [
                'key' => 'invitation_analytics',
                'label' => 'Analytics',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/invitation-analytics',
                'permission' => 'view_invitation',
                'order' => 4,
                'page_title' => NULL,
            ],
        ],
    ],
    'layout' => [
        'top_bar' => [
            'enabled' => true,
        ],
        'context_menu' => [
            'type' => 'sidebar',
            'position' => 'left',
            'allow_switch' => true,
            'default_type' => 'sidebar',
        ],
        'sidebar' => [
            'initial_state' => 'full',
        ],
        'bottom_bar' => [
            'enabled' => true,
        ],
        'breadcrumb' => [
            'enabled' => true,
        ],
        'title' => [
            'enabled' => true,
        ],
    ],
    'shared_items' => [
        'header' => [],
        'footer' => [],
    ],
    'shared_top_items' => [
        'left' => [],
        'right' => [],
    ],
];
