<?php

return [
    'context_groups' => [
        'Organization' => [
            'label' => 'Organization',
            'icon' => 'fas fa-building',
            'order' => 10000,
            'route' => NULL,
            'url' => 'hr/dashboard-organization-overview',
        ],
        'policies' => [
            'label' => 'Policies',
            'icon' => 'fas fa-gavel',
            'order' => 10000,
            'route' => NULL,
            'url' => 'hr/dashboard-policies-overview',
        ],
        'reports' => [
            'label' => 'Reports',
            'icon' => 'fas fa-file-alt',
            'order' => 10000,
            'route' => NULL,
            'url' => 'reports',
        ],
        'people' => [
            'label' => 'People',
            'icon' => 'fas fa-user-tie',
            'order' => 999,
            'route' => NULL,
            'url' => 'hr/dashboard-people-overview',
        ],
        'payroll' => [
            'label' => 'Payroll',
            'icon' => 'fas fa-file-invoice-dollar',
            'order' => 999,
            'route' => NULL,
            'url' => 'hr/dashboard-payroll-overview',
        ],
        'leave' => [
            'label' => 'Leave',
            'icon' => 'fas fa-user-check',
            'order' => 1000,
            'route' => NULL,
            'url' => 'hr/dashboard-leave-overview',
        ],
        'time' => [
            'label' => 'Time',
            'icon' => 'fas fa-user-clock',
            'order' => 999,
            'route' => NULL,
            'url' => 'hr/dashboard-time-overview',
        ],
    ],
    'contexts' => [
        'Organization' => [
            [
                'key' => 'company_profile_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-organization-overview',
                'permission' => 'view_company_profile_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'location',
                'label' => 'Locations',
                'icon' => 'fas fa-map-marker-alt',
                'route' => '/hr/locations',
                'permission' => 'view_location',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'company',
                'label' => 'Companies',
                'icon' => 'fas fa-building',
                'route' => '/hr/companies',
                'permission' => 'manage-system',
                'order' => 3,
                'page_title' => NULL,
            ],
            [
                'key' => 'department',
                'label' => 'Departments',
                'icon' => 'fas fa-sitemap',
                'route' => '/hr/departments',
                'permission' => 'view_department',
                'order' => 4,
                'page_title' => NULL,
            ],
        ],
        'policies' => [
            [
                'key' => 'attendance_policy',
                'label' => 'Attendance Policies',
                'icon' => 'fas fa-gavel',
                'route' => '/hr/attendance-policies',
                'permission' => 'view_attendance_policy',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'policy_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-policies-overview',
                'permission' => 'view_policy_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'policy_assignment',
                'label' => 'Policy Assignments',
                'icon' => 'fas fa-tasks',
                'route' => '/hr/policy-assignments',
                'permission' => 'view_policy_assignment',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'work_pattern',
                'label' => 'Work Patterns',
                'icon' => 'fas fa-calendar-week',
                'route' => '/hr/work-patterns',
                'permission' => 'view_work_pattern',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_work_pattern',
                'label' => 'Employee Work Patterns',
                'icon' => 'fas fa-user-tag',
                'route' => '/hr/employee-work-patterns',
                'permission' => 'view_employee_work_pattern',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'reports' => [
            [
                'key' => 'saved_report',
                'label' => 'Saved Reports',
                'icon' => 'fas fa-user',
                'route' => '/saved-reports',
                'permission' => 'view_saved_report',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'people' => [
            [
                'key' => 'people_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-people-overview',
                'permission' => 'view_people_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_group',
                'label' => 'Employee Groups',
                'icon' => 'fas fa-layer-group',
                'route' => '/hr/employee-groups',
                'permission' => 'view_employee_group',
                'order' => 6,
                'page_title' => NULL,
            ],
            [
                'key' => 'tag',
                'label' => 'Tags',
                'icon' => 'fas fa-tags',
                'route' => '/hr/tags',
                'permission' => 'view_tag',
                'order' => 7,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee',
                'label' => 'Employees',
                'icon' => 'fas fa-user-tie',
                'route' => '/hr/employees',
                'permission' => 'view_employee',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_job_history',
                'label' => 'Job History',
                'icon' => 'fas fa-history',
                'route' => '/hr/employee-job-histories',
                'permission' => 'view_employee_job_history',
                'order' => 8,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_profile',
                'label' => 'Profiles',
                'icon' => 'fas fa-id-card',
                'route' => '/hr/employee-profiles',
                'permission' => 'view_employee_profile',
                'order' => 3,
                'page_title' => NULL,
            ],
            [
                'key' => 'team',
                'label' => 'Teams',
                'icon' => 'fas fa-user-friends',
                'route' => '/hr/teams',
                'permission' => 'view_team',
                'order' => 5,
                'page_title' => NULL,
            ],
            [
                'key' => 'document',
                'label' => 'Documents',
                'icon' => 'fas fa-folder-open',
                'route' => '/hr/documents',
                'permission' => 'view_document',
                'order' => 9,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_position',
                'label' => 'Current Jobs',
                'icon' => 'fas fa-briefcase',
                'route' => '/hr/employee-positions',
                'permission' => 'view_employee_position',
                'order' => 4,
                'page_title' => NULL,
            ],
            [
                'key' => 'job_title',
                'label' => 'Job Titles',
                'icon' => 'fas fa-briefcase',
                'route' => '/hr/job-titles',
                'permission' => 'view_job_title',
                'order' => 10,
                'page_title' => NULL,
            ],
        ],
        'payroll' => [
            [
                'key' => 'payroll_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-payroll-overview',
                'permission' => 'view_payroll_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'pay_schedule',
                'label' => 'Pay Schedules',
                'icon' => 'fas fa-calendar-alt',
                'route' => '/hr/pay-schedules',
                'permission' => 'view_pay_schedule',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_payroll_profile',
                'label' => 'Employee Profiles',
                'icon' => 'fas fa-user-tie',
                'route' => '/hr/employee-payroll-profiles',
                'permission' => 'view_employee_payroll_profile',
                'order' => 3,
                'page_title' => NULL,
            ],
            [
                'key' => 'payroll_run',
                'label' => 'Payroll Runs',
                'icon' => 'fas fa-file-invoice-dollar',
                'route' => '/hr/payroll-runs',
                'permission' => 'view_payroll_run',
                'order' => 4,
                'page_title' => NULL,
            ],
            [
                'key' => 'payroll_payslip',
                'label' => 'Payslips',
                'icon' => 'fas fa-receipt',
                'route' => '/hr/payroll-payslips',
                'permission' => 'view_payroll_payslip',
                'order' => 5,
                'page_title' => NULL,
            ],
            [
                'key' => 'payroll_policy',
                'label' => 'Payroll Policies',
                'icon' => 'fas fa-gavel',
                'route' => '/hr/payroll-policies',
                'permission' => 'view_payroll_policy',
                'order' => 6,
                'page_title' => NULL,
            ],
            [
                'key' => 'payroll_run_adjustment',
                'label' => 'One‑Time Adjustments',
                'icon' => 'fas fa-edit',
                'route' => '/hr/payroll-run-adjustments',
                'permission' => 'view_payroll_run_adjustment',
                'order' => 7,
                'page_title' => NULL,
            ],
            [
                'key' => 'employee_adjustment_profile',
                'label' => 'Recurring Adjustments',
                'icon' => 'fas fa-sync-alt',
                'route' => '/hr/employee-adjustment-profiles',
                'permission' => 'view_employee_adjustment_profile',
                'order' => 8,
                'page_title' => NULL,
            ],
            [
                'key' => 'payslip_item',
                'label' => 'Payslip Items',
                'icon' => 'fas fa-list-ul',
                'route' => '/hr/payslip-items',
                'permission' => 'view_payslip_item',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'payroll_policy_assignment',
                'label' => 'Policy Assignments',
                'icon' => 'fas fa-link',
                'route' => '/hr/payroll-policy-assignments',
                'permission' => 'view_payroll_policy_assignment',
                'order' => 9,
                'page_title' => NULL,
            ],
        ],
        'leave' => [
            [
                'key' => 'leave_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-leave-overview',
                'permission' => 'view_leave_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'leave_type',
                'label' => 'Leave Types',
                'icon' => 'fas fa-tags',
                'route' => '/hr/leave-types',
                'permission' => 'view_leave_type',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'leave_request',
                'label' => 'Leave Requests',
                'icon' => 'fas fa-calendar-alt',
                'route' => '/hr/leave-requests',
                'permission' => 'view_leave_request',
                'order' => 3,
                'page_title' => NULL,
            ],
            [
                'key' => 'leave_balance',
                'label' => 'Leave Balances',
                'icon' => 'fas fa-balance-scale',
                'route' => '/leave-balances',
                'permission' => 'view_leave_balance',
                'order' => 999,
                'page_title' => NULL,
            ],
            [
                'key' => 'leave_approver',
                'label' => 'Approval Rules',
                'icon' => 'fas fa-user-check',
                'route' => '/hr/leave-approvers',
                'permission' => 'view_leave_approver',
                'order' => 4,
                'page_title' => NULL,
            ],
        ],
        'time' => [
            [
                'key' => 'attendance_overview',
                'label' => 'Overview',
                'icon' => 'fas fa-chart-bar',
                'route' => '/hr/dashboard-time-overview',
                'permission' => 'view_attendance_overview',
                'order' => 1,
                'page_title' => NULL,
            ],
            [
                'key' => 'saved_report',
                'label' => 'Reports',
                'icon' => 'fas fa-file-alt me-2',
                'route' => '/reports',
                'permission' => 'view_saved_report',
                'order' => 10000000,
                'page_title' => NULL,
            ],
            [
                'key' => 'attendance',
                'label' => 'Attendance',
                'icon' => 'fas fa-user-clock',
                'route' => '/hr/attendances',
                'permission' => 'view_attendance',
                'order' => 2,
                'page_title' => NULL,
            ],
            [
                'key' => 'shift_schedule',
                'label' => 'Shift Schedules',
                'icon' => 'fas fa-calendar-check',
                'route' => '/hr/shift-schedules',
                'permission' => 'view_shift_schedule',
                'order' => 5,
                'page_title' => NULL,
            ],
            [
                'key' => 'holiday_calendar',
                'label' => 'Holiday Calendars',
                'icon' => 'fas fa-calendar-alt',
                'route' => '/hr/holiday-calendars',
                'permission' => 'view_holiday_calendar',
                'order' => 4,
                'page_title' => NULL,
            ],
            [
                'key' => 'holiday',
                'label' => 'Holidays',
                'icon' => 'fas fa-gift',
                'route' => '/hr/holidays',
                'permission' => 'view_holiday',
                'order' => 3,
                'page_title' => NULL,
            ],
            [
                'key' => 'shift',
                'label' => 'Shifts',
                'icon' => 'fas fa-calendar-day',
                'route' => '/hr/shifts',
                'permission' => 'view_shift',
                'order' => 6,
                'page_title' => NULL,
            ],
        ],
        'attendance_adjustment' => [
            [
                'key' => 'attendance_adjustment',
                'label' => 'Attendance Adjustments',
                'icon' => 'fas fa-edit',
                'route' => '/attendance-adjustments',
                'permission' => 'view_attendance_adjustment',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'clock_event' => [
            [
                'key' => 'clock_event',
                'label' => 'Clock Events',
                'icon' => 'fas fa-clock',
                'route' => '/clock-events',
                'permission' => 'view_clock_event',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
        'attendance_session' => [
            [
                'key' => 'attendance_session',
                'label' => 'Attendance Sessions',
                'icon' => 'fas fa-hourglass-half',
                'route' => '/attendance-sessions',
                'permission' => 'view_attendance_session',
                'order' => 999,
                'page_title' => NULL,
            ],
        ],
    ],
    'layout' => [
        'top_bar' => [
            'enabled' => true,
        ],
        'context_menu' => [
            'type' => 'sidebar',
            'position' => 'left',
            'allow_switch' => true,
            'default_type' => 'sidebar',
        ],
        'sidebar' => [
            'initial_state' => 'full',
        ],
        'bottom_bar' => [
            'enabled' => true,
        ],
        'breadcrumb' => [
            'enabled' => true,
        ],
        'title' => [
            'enabled' => true,
        ],
    ],
    'shared_items' => [
        'header' => [],
        'footer' => [],
    ],
    'shared_top_items' => [
        'left' => [],
        'right' => [],
    ],
];
